
<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2015 v4.2.99
     Generated on:       1/26/2016 5:02 PM
     Generated by:       Vadim Smal
     Organization:       Advance America
    --------------------------------------------------------------------------------
    .DESCRIPTION
        GUI script generated by PowerShell Studio 2015
#>
#----------------------------------------------
#region Application Functions
#----------------------------------------------

#endregion Application Functions

#----------------------------------------------
# Generated Form Function
#----------------------------------------------
function Call-PowerShellCreateDACLHTML_psf {

	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Xml, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.DirectoryServices, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	[void][reflection.assembly]::Load('System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.ServiceProcess, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$formGetDACL = New-Object 'System.Windows.Forms.Form'
	$textboxFolderPath = New-Object 'System.Windows.Forms.TextBox'
	$labelFolderPath = New-Object 'System.Windows.Forms.Label'
	$buttonGetAccessList = New-Object 'System.Windows.Forms.Button'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	
	
	
	$labelFolderPath_Click={
		#TODO: Place custom script here
		
	}
	
	$buttonGetAccessList_Click={
		#TODO: Place custom script here
		
	}
	
	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$formGetDACL.WindowState = $InitialFormWindowState
	}
	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$labelFolderPath.remove_Click($labelFolderPath_Click)
			$buttonGetAccessList.remove_Click($buttonGetAccessList_Click)
			$formGetDACL.remove_Load($Form_StateCorrection_Load)
			$formGetDACL.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch [Exception]
		{ }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$formGetDACL.SuspendLayout()
	#
	# formGetDACL
	#
	$formGetDACL.Controls.Add($textboxFolderPath)
	$formGetDACL.Controls.Add($labelFolderPath)
	$formGetDACL.Controls.Add($buttonGetAccessList)
	$formGetDACL.ClientSize = '584, 101'
	$formGetDACL.MinimizeBox = $False
	$formGetDACL.Name = 'formGetDACL'
	$formGetDACL.SizeGripStyle = 'Hide'
	$formGetDACL.Text = 'Get DACL'
	#
	# textboxFolderPath
	#
	$textboxFolderPath.Location = '12, 37'
	$textboxFolderPath.Name = 'textboxFolderPath'
	$textboxFolderPath.Size = '559, 20'
	$textboxFolderPath.TabIndex = 2
	#
	# labelFolderPath
	#
	$labelFolderPath.Location = '13, 11'
	$labelFolderPath.Name = 'labelFolderPath'
	$labelFolderPath.Size = '100, 23'
	$labelFolderPath.TabIndex = 1
	$labelFolderPath.Text = 'Enter Folder Path'
	$labelFolderPath.add_Click($labelFolderPath_Click)
	#
	# buttonGetAccessList
	#
	$buttonGetAccessList.Location = '424, 63'
	$buttonGetAccessList.Name = 'buttonGetAccessList'
	$buttonGetAccessList.Size = '147, 23'
	$buttonGetAccessList.TabIndex = 0
	$buttonGetAccessList.Text = 'Get Access List'
	$buttonGetAccessList.UseVisualStyleBackColor = $True
	$buttonGetAccessList.add_Click($buttonGetAccessList_Click)
	$formGetDACL.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $formGetDACL.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$formGetDACL.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$formGetDACL.add_FormClosed($Form_Cleanup_FormClosed)
	#Show the Form
	return $formGetDACL.ShowDialog()

} #End Function

#Call the form
Call-PowerShellCreateDACLHTML_psf | Out-Null
